/*

 BALL.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char ball[] =
{
  0x07,0x07,0x18,0x1F,0x20,0x3F,0x5C,0x6F,
  0x5E,0x73,0x9E,0xF1,0x8F,0xF9,0x83,0xFE,
  0x07,0x07,0x19,0x1E,0x21,0x3F,0x43,0x7E,
  0x43,0x7E,0x87,0xF8,0x9F,0xF9,0xFF,0xA2
};

/* End of BALL.C */
