/*

 CURSOR.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char cursor[] =
{
  0x00,0x00,0xC0,0xC0,0xF0,0xF0,0xFC,0xFC,
  0xFF,0xFF,0xFC,0xFC,0xF0,0xF0,0xC0,0xC0
};

/* End of CURSOR.C */
