/*

 PLAYER_TAGS.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char player_tags[] =
{
  0xFE,0x10,0xFE,0x38,0xFE,0x00,0xFE,0xC4,
  0xFE,0xAC,0xFE,0xC4,0xFE,0x84,0xFE,0x8E,
  0xFE,0x10,0xFE,0x38,0xFE,0x00,0xFE,0xCC,
  0xFE,0xA2,0xFE,0xC6,0xFE,0x88,0xFE,0x8E
};

/* End of PLAYER_TAGS.C */
